/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCalendarioRouteImport } from './routes/_app.calendario'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppIdeiasRouteImport } from './routes/_app.ideias'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppProducaoRouteImport } from './routes/_app.producao'
import { Route as AppRadarRouteImport } from './routes/_app.radar'
import { Route as AppRoteirosRouteImport } from './routes/_app.roteiros'
import { Route as AppIdeiasIdRouteImport } from './routes/_app.ideias.$id'
import { Route as AppProducaoIdRouteImport } from './routes/_app.producao.$id'
import { Route as AppRadarIdRouteImport } from './routes/_app.radar.$id'
import { Route as AppRoteirosIdRouteImport } from './routes/_app.roteiros.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeiasRoute = AppIdeiasRouteImport.update({
  id: '/ideias',
  path: '/ideias',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppRadarRoute = AppRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AppRoute,
} as any)
const AppRoteirosRoute = AppRoteirosRouteImport.update({
  id: '/roteiros',
  path: '/roteiros',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeiasIdRoute = AppIdeiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIdeiasRoute,
} as any)
const AppProducaoIdRoute = AppProducaoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProducaoRoute,
} as any)
const AppRadarIdRoute = AppRadarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRadarRoute,
} as any)
const AppRoteirosIdRoute = AppRoteirosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRoteirosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/calendario': typeof AppCalendarioRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/ideias': typeof AppIdeiasRouteWithChildren
  '/performance': typeof AppPerformanceRoute
  '/producao': typeof AppProducaoRouteWithChildren
  '/radar': typeof AppRadarRouteWithChildren
  '/roteiros': typeof AppRoteirosRouteWithChildren
  '/ideias/$id': typeof AppIdeiasIdRoute
  '/producao/$id': typeof AppProducaoIdRoute
  '/radar/$id': typeof AppRadarIdRoute
  '/roteiros/$id': typeof AppRoteirosIdRoute
}
export interface FileRoutesByTo {
  '/calendario': typeof AppCalendarioRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/ideias': typeof AppIdeiasRouteWithChildren
  '/performance': typeof AppPerformanceRoute
  '/producao': typeof AppProducaoRouteWithChildren
  '/radar': typeof AppRadarRouteWithChildren
  '/roteiros': typeof AppRoteirosRouteWithChildren
  '/': typeof AppIndexRoute
  '/ideias/$id': typeof AppIdeiasIdRoute
  '/producao/$id': typeof AppProducaoIdRoute
  '/radar/$id': typeof AppRadarIdRoute
  '/roteiros/$id': typeof AppRoteirosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/ideias': typeof AppIdeiasRouteWithChildren
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/producao': typeof AppProducaoRouteWithChildren
  '/_app/radar': typeof AppRadarRouteWithChildren
  '/_app/roteiros': typeof AppRoteirosRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/ideias/$id': typeof AppIdeiasIdRoute
  '/_app/producao/$id': typeof AppProducaoIdRoute
  '/_app/radar/$id': typeof AppRadarIdRoute
  '/_app/roteiros/$id': typeof AppRoteirosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/ideias'
    | '/performance'
    | '/producao'
    | '/radar'
    | '/roteiros'
    | '/ideias/$id'
    | '/producao/$id'
    | '/radar/$id'
    | '/roteiros/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/calendario'
    | '/configuracoes'
    | '/ideias'
    | '/performance'
    | '/producao'
    | '/radar'
    | '/roteiros'
    | '/'
    | '/ideias/$id'
    | '/producao/$id'
    | '/radar/$id'
    | '/roteiros/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/calendario'
    | '/_app/configuracoes'
    | '/_app/ideias'
    | '/_app/performance'
    | '/_app/producao'
    | '/_app/radar'
    | '/_app/roteiros'
    | '/_app/'
    | '/_app/ideias/$id'
    | '/_app/producao/$id'
    | '/_app/radar/$id'
    | '/_app/roteiros/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideias': {
      id: '/_app/ideias'
      path: '/ideias'
      fullPath: '/ideias'
      preLoaderRoute: typeof AppIdeiasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao': {
      id: '/_app/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/radar': {
      id: '/_app/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AppRadarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roteiros': {
      id: '/_app/roteiros'
      path: '/roteiros'
      fullPath: '/roteiros'
      preLoaderRoute: typeof AppRoteirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideias/$id': {
      id: '/_app/ideias/$id'
      path: '/$id'
      fullPath: '/ideias/$id'
      preLoaderRoute: typeof AppIdeiasIdRouteImport
      parentRoute: typeof AppIdeiasRoute
    }
    '/_app/producao/$id': {
      id: '/_app/producao/$id'
      path: '/$id'
      fullPath: '/producao/$id'
      preLoaderRoute: typeof AppProducaoIdRouteImport
      parentRoute: typeof AppProducaoRoute
    }
    '/_app/radar/$id': {
      id: '/_app/radar/$id'
      path: '/$id'
      fullPath: '/radar/$id'
      preLoaderRoute: typeof AppRadarIdRouteImport
      parentRoute: typeof AppRadarRoute
    }
    '/_app/roteiros/$id': {
      id: '/_app/roteiros/$id'
      path: '/$id'
      fullPath: '/roteiros/$id'
      preLoaderRoute: typeof AppRoteirosIdRouteImport
      parentRoute: typeof AppRoteirosRoute
    }
  }
}

interface AppIdeiasRouteChildren {
  AppIdeiasIdRoute: typeof AppIdeiasIdRoute
}

const AppIdeiasRouteChildren: AppIdeiasRouteChildren = {
  AppIdeiasIdRoute: AppIdeiasIdRoute,
}

const AppIdeiasRouteWithChildren = AppIdeiasRoute._addFileChildren(
  AppIdeiasRouteChildren,
)

interface AppProducaoRouteChildren {
  AppProducaoIdRoute: typeof AppProducaoIdRoute
}

const AppProducaoRouteChildren: AppProducaoRouteChildren = {
  AppProducaoIdRoute: AppProducaoIdRoute,
}

const AppProducaoRouteWithChildren = AppProducaoRoute._addFileChildren(
  AppProducaoRouteChildren,
)

interface AppRadarRouteChildren {
  AppRadarIdRoute: typeof AppRadarIdRoute
}

const AppRadarRouteChildren: AppRadarRouteChildren = {
  AppRadarIdRoute: AppRadarIdRoute,
}

const AppRadarRouteWithChildren = AppRadarRoute._addFileChildren(
  AppRadarRouteChildren,
)

interface AppRoteirosRouteChildren {
  AppRoteirosIdRoute: typeof AppRoteirosIdRoute
}

const AppRoteirosRouteChildren: AppRoteirosRouteChildren = {
  AppRoteirosIdRoute: AppRoteirosIdRoute,
}

const AppRoteirosRouteWithChildren = AppRoteirosRoute._addFileChildren(
  AppRoteirosRouteChildren,
)

interface AppRouteChildren {
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppIdeiasRoute: typeof AppIdeiasRouteWithChildren
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppProducaoRoute: typeof AppProducaoRouteWithChildren
  AppRadarRoute: typeof AppRadarRouteWithChildren
  AppRoteirosRoute: typeof AppRoteirosRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarioRoute: AppCalendarioRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppIdeiasRoute: AppIdeiasRouteWithChildren,
  AppPerformanceRoute: AppPerformanceRoute,
  AppProducaoRoute: AppProducaoRouteWithChildren,
  AppRadarRoute: AppRadarRouteWithChildren,
  AppRoteirosRoute: AppRoteirosRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
