/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAvataresRouteImport } from './routes/_app.avatares'
import { Route as AppCalendarioRouteImport } from './routes/_app.calendario'
import { Route as AppCinematicRouteImport } from './routes/_app.cinematic'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCortesRouteImport } from './routes/_app.cortes'
import { Route as AppIdeiasRouteImport } from './routes/_app.ideias'
import { Route as AppKitLocalRouteImport } from './routes/_app.kit-local'
import { Route as AppNoticiasRouteImport } from './routes/_app.noticias'
import { Route as AppPacksRouteImport } from './routes/_app.packs'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppProducaoRouteImport } from './routes/_app.producao'
import { Route as AppRadarRouteImport } from './routes/_app.radar'
import { Route as AppRoteirosRouteImport } from './routes/_app.roteiros'
import { Route as AppIdeiasIndexRouteImport } from './routes/_app.ideias.index'
import { Route as AppIdeiasIdRouteImport } from './routes/_app.ideias.$id'
import { Route as AppProducaoIndexRouteImport } from './routes/_app.producao.index'
import { Route as AppProducaoIdRouteImport } from './routes/_app.producao.$id'
import { Route as AppRadarIndexRouteImport } from './routes/_app.radar.index'
import { Route as AppRadarIdRouteImport } from './routes/_app.radar.$id'
import { Route as AppRoteirosIndexRouteImport } from './routes/_app.roteiros.index'
import { Route as AppRoteirosIdRouteImport } from './routes/_app.roteiros.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAvataresRoute = AppAvataresRouteImport.update({
  id: '/avatares',
  path: '/avatares',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppCinematicRoute = AppCinematicRouteImport.update({
  id: '/cinematic',
  path: '/cinematic',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCortesRoute = AppCortesRouteImport.update({
  id: '/cortes',
  path: '/cortes',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeiasRoute = AppIdeiasRouteImport.update({
  id: '/ideias',
  path: '/ideias',
  getParentRoute: () => AppRoute,
} as any)
const AppKitLocalRoute = AppKitLocalRouteImport.update({
  id: '/kit-local',
  path: '/kit-local',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticiasRoute = AppNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AppRoute,
} as any)
const AppPacksRoute = AppPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppRadarRoute = AppRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AppRoute,
} as any)
const AppRoteirosRoute = AppRoteirosRouteImport.update({
  id: '/roteiros',
  path: '/roteiros',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeiasIndexRoute = AppIdeiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdeiasRoute,
} as any)
const AppIdeiasIdRoute = AppIdeiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIdeiasRoute,
} as any)
const AppProducaoIndexRoute = AppProducaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProducaoRoute,
} as any)
const AppProducaoIdRoute = AppProducaoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProducaoRoute,
} as any)
const AppRadarIndexRoute = AppRadarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRadarRoute,
} as any)
const AppRadarIdRoute = AppRadarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRadarRoute,
} as any)
const AppRoteirosIndexRoute = AppRoteirosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoteirosRoute,
} as any)
const AppRoteirosIdRoute = AppRoteirosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRoteirosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/avatares': typeof AppAvataresRoute
  '/calendario': typeof AppCalendarioRoute
  '/cinematic': typeof AppCinematicRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/cortes': typeof AppCortesRoute
  '/ideias': typeof AppIdeiasRouteWithChildren
  '/kit-local': typeof AppKitLocalRoute
  '/noticias': typeof AppNoticiasRoute
  '/packs': typeof AppPacksRoute
  '/performance': typeof AppPerformanceRoute
  '/producao': typeof AppProducaoRouteWithChildren
  '/radar': typeof AppRadarRouteWithChildren
  '/roteiros': typeof AppRoteirosRouteWithChildren
  '/ideias/$id': typeof AppIdeiasIdRoute
  '/producao/$id': typeof AppProducaoIdRoute
  '/radar/$id': typeof AppRadarIdRoute
  '/roteiros/$id': typeof AppRoteirosIdRoute
  '/ideias/': typeof AppIdeiasIndexRoute
  '/producao/': typeof AppProducaoIndexRoute
  '/radar/': typeof AppRadarIndexRoute
  '/roteiros/': typeof AppRoteirosIndexRoute
}
export interface FileRoutesByTo {
  '/avatares': typeof AppAvataresRoute
  '/calendario': typeof AppCalendarioRoute
  '/cinematic': typeof AppCinematicRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/cortes': typeof AppCortesRoute
  '/kit-local': typeof AppKitLocalRoute
  '/noticias': typeof AppNoticiasRoute
  '/packs': typeof AppPacksRoute
  '/performance': typeof AppPerformanceRoute
  '/': typeof AppIndexRoute
  '/ideias/$id': typeof AppIdeiasIdRoute
  '/producao/$id': typeof AppProducaoIdRoute
  '/radar/$id': typeof AppRadarIdRoute
  '/roteiros/$id': typeof AppRoteirosIdRoute
  '/ideias': typeof AppIdeiasIndexRoute
  '/producao': typeof AppProducaoIndexRoute
  '/radar': typeof AppRadarIndexRoute
  '/roteiros': typeof AppRoteirosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/avatares': typeof AppAvataresRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/cinematic': typeof AppCinematicRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/cortes': typeof AppCortesRoute
  '/_app/ideias': typeof AppIdeiasRouteWithChildren
  '/_app/kit-local': typeof AppKitLocalRoute
  '/_app/noticias': typeof AppNoticiasRoute
  '/_app/packs': typeof AppPacksRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/producao': typeof AppProducaoRouteWithChildren
  '/_app/radar': typeof AppRadarRouteWithChildren
  '/_app/roteiros': typeof AppRoteirosRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/ideias/$id': typeof AppIdeiasIdRoute
  '/_app/producao/$id': typeof AppProducaoIdRoute
  '/_app/radar/$id': typeof AppRadarIdRoute
  '/_app/roteiros/$id': typeof AppRoteirosIdRoute
  '/_app/ideias/': typeof AppIdeiasIndexRoute
  '/_app/producao/': typeof AppProducaoIndexRoute
  '/_app/radar/': typeof AppRadarIndexRoute
  '/_app/roteiros/': typeof AppRoteirosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatares'
    | '/calendario'
    | '/cinematic'
    | '/configuracoes'
    | '/cortes'
    | '/ideias'
    | '/kit-local'
    | '/noticias'
    | '/packs'
    | '/performance'
    | '/producao'
    | '/radar'
    | '/roteiros'
    | '/ideias/$id'
    | '/producao/$id'
    | '/radar/$id'
    | '/roteiros/$id'
    | '/ideias/'
    | '/producao/'
    | '/radar/'
    | '/roteiros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/avatares'
    | '/calendario'
    | '/cinematic'
    | '/configuracoes'
    | '/cortes'
    | '/kit-local'
    | '/noticias'
    | '/packs'
    | '/performance'
    | '/'
    | '/ideias/$id'
    | '/producao/$id'
    | '/radar/$id'
    | '/roteiros/$id'
    | '/ideias'
    | '/producao'
    | '/radar'
    | '/roteiros'
  id:
    | '__root__'
    | '/_app'
    | '/_app/avatares'
    | '/_app/calendario'
    | '/_app/cinematic'
    | '/_app/configuracoes'
    | '/_app/cortes'
    | '/_app/ideias'
    | '/_app/kit-local'
    | '/_app/noticias'
    | '/_app/packs'
    | '/_app/performance'
    | '/_app/producao'
    | '/_app/radar'
    | '/_app/roteiros'
    | '/_app/'
    | '/_app/ideias/$id'
    | '/_app/producao/$id'
    | '/_app/radar/$id'
    | '/_app/roteiros/$id'
    | '/_app/ideias/'
    | '/_app/producao/'
    | '/_app/radar/'
    | '/_app/roteiros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avatares': {
      id: '/_app/avatares'
      path: '/avatares'
      fullPath: '/avatares'
      preLoaderRoute: typeof AppAvataresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cinematic': {
      id: '/_app/cinematic'
      path: '/cinematic'
      fullPath: '/cinematic'
      preLoaderRoute: typeof AppCinematicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cortes': {
      id: '/_app/cortes'
      path: '/cortes'
      fullPath: '/cortes'
      preLoaderRoute: typeof AppCortesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideias': {
      id: '/_app/ideias'
      path: '/ideias'
      fullPath: '/ideias'
      preLoaderRoute: typeof AppIdeiasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kit-local': {
      id: '/_app/kit-local'
      path: '/kit-local'
      fullPath: '/kit-local'
      preLoaderRoute: typeof AppKitLocalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/noticias': {
      id: '/_app/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AppNoticiasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packs': {
      id: '/_app/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof AppPacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao': {
      id: '/_app/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/radar': {
      id: '/_app/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AppRadarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roteiros': {
      id: '/_app/roteiros'
      path: '/roteiros'
      fullPath: '/roteiros'
      preLoaderRoute: typeof AppRoteirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideias/': {
      id: '/_app/ideias/'
      path: '/'
      fullPath: '/ideias/'
      preLoaderRoute: typeof AppIdeiasIndexRouteImport
      parentRoute: typeof AppIdeiasRoute
    }
    '/_app/ideias/$id': {
      id: '/_app/ideias/$id'
      path: '/$id'
      fullPath: '/ideias/$id'
      preLoaderRoute: typeof AppIdeiasIdRouteImport
      parentRoute: typeof AppIdeiasRoute
    }
    '/_app/producao/': {
      id: '/_app/producao/'
      path: '/'
      fullPath: '/producao/'
      preLoaderRoute: typeof AppProducaoIndexRouteImport
      parentRoute: typeof AppProducaoRoute
    }
    '/_app/producao/$id': {
      id: '/_app/producao/$id'
      path: '/$id'
      fullPath: '/producao/$id'
      preLoaderRoute: typeof AppProducaoIdRouteImport
      parentRoute: typeof AppProducaoRoute
    }
    '/_app/radar/': {
      id: '/_app/radar/'
      path: '/'
      fullPath: '/radar/'
      preLoaderRoute: typeof AppRadarIndexRouteImport
      parentRoute: typeof AppRadarRoute
    }
    '/_app/radar/$id': {
      id: '/_app/radar/$id'
      path: '/$id'
      fullPath: '/radar/$id'
      preLoaderRoute: typeof AppRadarIdRouteImport
      parentRoute: typeof AppRadarRoute
    }
    '/_app/roteiros/': {
      id: '/_app/roteiros/'
      path: '/'
      fullPath: '/roteiros/'
      preLoaderRoute: typeof AppRoteirosIndexRouteImport
      parentRoute: typeof AppRoteirosRoute
    }
    '/_app/roteiros/$id': {
      id: '/_app/roteiros/$id'
      path: '/$id'
      fullPath: '/roteiros/$id'
      preLoaderRoute: typeof AppRoteirosIdRouteImport
      parentRoute: typeof AppRoteirosRoute
    }
  }
}

interface AppIdeiasRouteChildren {
  AppIdeiasIdRoute: typeof AppIdeiasIdRoute
  AppIdeiasIndexRoute: typeof AppIdeiasIndexRoute
}

const AppIdeiasRouteChildren: AppIdeiasRouteChildren = {
  AppIdeiasIdRoute: AppIdeiasIdRoute,
  AppIdeiasIndexRoute: AppIdeiasIndexRoute,
}

const AppIdeiasRouteWithChildren = AppIdeiasRoute._addFileChildren(
  AppIdeiasRouteChildren,
)

interface AppProducaoRouteChildren {
  AppProducaoIdRoute: typeof AppProducaoIdRoute
  AppProducaoIndexRoute: typeof AppProducaoIndexRoute
}

const AppProducaoRouteChildren: AppProducaoRouteChildren = {
  AppProducaoIdRoute: AppProducaoIdRoute,
  AppProducaoIndexRoute: AppProducaoIndexRoute,
}

const AppProducaoRouteWithChildren = AppProducaoRoute._addFileChildren(
  AppProducaoRouteChildren,
)

interface AppRadarRouteChildren {
  AppRadarIdRoute: typeof AppRadarIdRoute
  AppRadarIndexRoute: typeof AppRadarIndexRoute
}

const AppRadarRouteChildren: AppRadarRouteChildren = {
  AppRadarIdRoute: AppRadarIdRoute,
  AppRadarIndexRoute: AppRadarIndexRoute,
}

const AppRadarRouteWithChildren = AppRadarRoute._addFileChildren(
  AppRadarRouteChildren,
)

interface AppRoteirosRouteChildren {
  AppRoteirosIdRoute: typeof AppRoteirosIdRoute
  AppRoteirosIndexRoute: typeof AppRoteirosIndexRoute
}

const AppRoteirosRouteChildren: AppRoteirosRouteChildren = {
  AppRoteirosIdRoute: AppRoteirosIdRoute,
  AppRoteirosIndexRoute: AppRoteirosIndexRoute,
}

const AppRoteirosRouteWithChildren = AppRoteirosRoute._addFileChildren(
  AppRoteirosRouteChildren,
)

interface AppRouteChildren {
  AppAvataresRoute: typeof AppAvataresRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppCinematicRoute: typeof AppCinematicRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCortesRoute: typeof AppCortesRoute
  AppIdeiasRoute: typeof AppIdeiasRouteWithChildren
  AppKitLocalRoute: typeof AppKitLocalRoute
  AppNoticiasRoute: typeof AppNoticiasRoute
  AppPacksRoute: typeof AppPacksRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppProducaoRoute: typeof AppProducaoRouteWithChildren
  AppRadarRoute: typeof AppRadarRouteWithChildren
  AppRoteirosRoute: typeof AppRoteirosRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvataresRoute: AppAvataresRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppCinematicRoute: AppCinematicRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCortesRoute: AppCortesRoute,
  AppIdeiasRoute: AppIdeiasRouteWithChildren,
  AppKitLocalRoute: AppKitLocalRoute,
  AppNoticiasRoute: AppNoticiasRoute,
  AppPacksRoute: AppPacksRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppProducaoRoute: AppProducaoRouteWithChildren,
  AppRadarRoute: AppRadarRouteWithChildren,
  AppRoteirosRoute: AppRoteirosRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
